export const CATEGORIAS = {
  nf_antecipada:       { label: 'NF Antecipada',         cor: '#E8000D', sla: 4  },
  repasse:             { label: 'Repasse',               cor: '#FF9500', sla: 8  },
  reembolso_royalties: { label: 'Reembolso Royalties',   cor: '#D4537E', sla: 24 },
  reembolso_cliente:   { label: 'Reembolso Cliente',     cor: '#993C1D', sla: 8  },
  cancelamento_nf:     { label: 'Cancelamento NF',       cor: '#378ADD', sla: 24 },
  ajuste_nf:           { label: 'Ajuste NF',             cor: '#7B61FF', sla: 24 },
  emissao_nf:          { label: 'Emissão NF',            cor: '#1D9E75', sla: 48 },
  finance:             { label: 'Finance',               cor: '#0F6E56', sla: 24 },
  fora_escopo:         { label: 'Fora do Escopo',        cor: '#6B6B6B', sla: 0  },
  analise_manual:      { label: 'Análise Manual',        cor: '#444444', sla: 48 },
}

export const CHAMADOS = [
  {
    id: 1, ticket_id: 'PYNW7833', prioridade: 'P1',
    categoria: 'repasse', subcategoria: '',
    status: 'nao_iniciado', dias: 4.0,
    titulo: 'Repasses pendentes.',
    unidade: 'KTM & Co.',
    usuario: '',
    descricao: 'Pessoal, preciso de um apoio e de uma posição mais clara, por favor. Pois no meu grupo de cobrança o pessoal não me posiciona e não resolve.  Estou com dois repasses pendentes do mês passado que ainda não tiveram conclusão no grupo de cobranças, e isso está impactando diretamente o nosso fluxo de ca',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-06 08:50',
    entrou_financeiro: '2026-04-06 08:50',
    links: [],
  },
  {
    id: 2, ticket_id: 'LQWG7506', prioridade: 'P1',
    categoria: 'reembolso_cliente', subcategoria: '',
    status: 'nao_iniciado', dias: 3.7,
    titulo: 'Reembolso de Cliente',
    unidade: 'Novaes & Co.',
    usuario: '',
    descricao: 'Atendimento do ticket IZRR6112 Mandaram subir a tratativa de churn do cliente para que haja a devolução do dinheiro, ocorre que esse projeto ja foi encerrado pois se trata de um SABER, e ele nao esta aparecendo na lista dos clientes para subir o churn, cliente já esta nervoso pela morosidade, precis',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-06 16:51',
    entrou_financeiro: '2026-04-06 16:51',
    links: [],
  },
  {
    id: 3, ticket_id: 'TJGY6519', prioridade: 'P1',
    categoria: 'repasse', subcategoria: '',
    status: 'nao_iniciado', dias: 2.6,
    titulo: 'Repasse apra Unidade',
    unidade: 'Aguiar & Associados',
    usuario: '',
    descricao: 'Olá, Recebemos nossos repasses de alguns clientes, com divergência. Referente ao mês de Janeiro, Fevereiro, Março e Abril/2026. Vieram com valor menor. Mencionei todos na planilha. Segue link abaixo com as informações devidas. https://docs.google.com/spreadsheets/d/1wqMCfC-bYm1rWcaMXtesXg4wmsDN-QGIj',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-07 17:45',
    entrou_financeiro: '2026-04-07 17:45',
    links: [{"url": "https://docs.google.com/spreadsheets/d/1wqMCfC-bYm1rWcaMXtesXg4wmsDN-QGIj", "label": "Planilha Google", "icon": "\ud83d\udcca"}],
  },
  {
    id: 4, ticket_id: 'UFAB1329', prioridade: 'P1',
    categoria: 'reembolso_cliente', subcategoria: '',
    status: 'nao_iniciado', dias: 2.5,
    titulo: 'reembolso de roy',
    unidade: 'Camargo Freitas & Associados',
    usuario: '',
    descricao: 'o cliente esconderijo criativo solicitou o reembolso do fee integral devido nao estar satisfeito com o projeto, fizemos o reembolso e solicitamos o reembolso de roy.',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-07 21:00',
    entrou_financeiro: '2026-04-07 21:00',
    links: [],
  },
  {
    id: 5, ticket_id: 'EVYK8317', prioridade: 'P1',
    categoria: 'repasse', subcategoria: '',
    status: 'nao_iniciado', dias: 1.8,
    titulo: 'Repasse',
    unidade: 'Canovas Mendes & Associados',
    usuario: '',
    descricao: 'Boa tarde, tudo bem?  Conforme falado com a Luana, temos dois clientes que utilizam o banco Itau, e no momento que foram realizar o pagamento pelo boleto, acabou sendo compensado como pix para o pix da matriz. Sendo assim, solicito o repasse de ambos para nossa conta. Segue o comprovante abaixo.',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-08 14:45',
    entrou_financeiro: '2026-04-08 14:45',
    links: [],
  },
  {
    id: 6, ticket_id: 'VKHG2819', prioridade: 'P1',
    categoria: 'reembolso_cliente', subcategoria: '',
    status: 'nao_iniciado', dias: 1.8,
    titulo: 'REEMBOLSO LABTESTE',
    unidade: 'Souza Santos & Associados',
    usuario: '',
    descricao: 'Boa tarde, tudo bem? Sou da V4 COMPANY SOUZA SANTOS e preciso de auxilio com: Nosso cliente Alice A. Silva (LABTESTE) - CNPJ:08.569.228/0001-09. Emitiu dois boletos pelo Finance e pagou os dois. O dinheiro foi para a matriz e o cliente pediu urgentemente o reembolso em sua conta ou efetuaria o distr',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-08 12:54',
    entrou_financeiro: '2026-04-08 12:54',
    links: [],
  },
  {
    id: 7, ticket_id: 'KLLJ8847', prioridade: 'P1',
    categoria: 'nf_antecipada', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'NFs de variavel para pagamento de fatura',
    unidade: 'Ames & Associados',
    usuario: '',
    descricao: 'Olá, tudo bem?   Preciso das Notas Fiscais  antecipadas de ABRIL do seguinte cliente referente ao boleto de variável de performance ( cobrança avulsa)  para ele conseguir realizar o pagamento:       **Total Arte Centro De Distribuicao Integrada Ltda.**   CNPJ :15.269.433/0001-14  Fatura vencimento: ',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:06',
    entrou_financeiro: '2026-04-09 11:06',
    links: [],
  },
  {
    id: 8, ticket_id: 'WCIT6098', prioridade: 'P1',
    categoria: 'repasse', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'REPASSE CK',
    unidade: 'Ferraz Piai & Co.',
    usuario: '',
    descricao: 'Preciso do repasse do cliente CALVIN KLEIN, ele pagou dia 05/04, pagam diretamente para a matriz e precisamos do repasse para a nossa unidade.   Preciso o quanto antes, por favor.   Obrigada',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 10:57',
    entrou_financeiro: '2026-04-09 10:58',
    links: [],
  },
  {
    id: 9, ticket_id: 'YUJF8261', prioridade: 'P1',
    categoria: 'nf_antecipada', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'Emissao notas fachi ',
    unidade: 'Peretto & Associados',
    usuario: '',
    descricao: 'ola bom dia ,  Solicitamos a emissao das notas do ultimo pagamento do cliente Fachi . O mesmo precisa das notas para fechamento.',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:34',
    entrou_financeiro: '2026-04-09 11:34',
    links: [],
  },
  {
    id: 10, ticket_id: 'PWFU5146', prioridade: 'P1',
    categoria: 'nf_antecipada', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'Cliente JS DISTRIBUIDORA DE PECAS S/A',
    unidade: 'Kloh Cerino & Associados',
    usuario: '',
    descricao: 'Olá, cliente JS DISTRIBUIDORA DE PECAS S/A 04.185.877/0001-55 fee $11.123,98 vence 10/04 e precisa da nota fiscal para realizar o pagamento',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:26',
    entrou_financeiro: '2026-04-09 11:26',
    links: [],
  },
  {
    id: 11, ticket_id: 'PRSU2012', prioridade: 'P1',
    categoria: 'nf_antecipada', subcategoria: '',
    status: 'nao_iniciado', dias: 0.8,
    titulo: 'solicitação de emissão de nfs',
    unidade: 'Ferraz Piai & Co.',
    usuario: '',
    descricao: 'emitir UVLINE CNPJ 06.021.902/0001-90 R$1.757,32 (variável) - são quatros notas referente a março e abril',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 14:08',
    entrou_financeiro: '2026-04-09 14:08',
    links: [],
  },
  {
    id: 12, ticket_id: 'JMKF6374', prioridade: 'P1',
    categoria: 'nf_antecipada', subcategoria: '',
    status: 'nao_iniciado', dias: 0.8,
    titulo: 'Cliente só paga com Nota Fiscal',
    unidade: 'Godoy Rosendo & Co.',
    usuario: '',
    descricao: 'Emitir notas fiscais: ESCOLA COLMEIA (LUGAR DA INFANCIA) R$ 3.237,60 ESCOLA COLMEIA (ISAAS) (LUGAR DA INFANCIA) R$ 2.000,00 ESCOLA COLMEIA LTDA R$ 3.000,00 ESCOLA COLMEIA LTDA (ISAAS) R$ 2.000,00 ESCOLA COLMEIA MATER R$ 3.000,00 ESCOLA COLMEIA MATER (ISAAS) R$ 2.000,00 ABELHUDA R$ 2.300,00',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 12:47',
    entrou_financeiro: '2026-04-09 12:48',
    links: [],
  },
  {
    id: 13, ticket_id: 'ULFW2660', prioridade: 'P1',
    categoria: 'repasse', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'Repasse de multa rescisória ',
    unidade: 'Alfradique & Associados',
    usuario: '',
    descricao: 'Boa tarde, gostaria de uma data do repasse da multa rescisória paga pelo cliente LDX CAPITAL	41.468.144/0001-54, a multa já foi paga, mas gostaria de saber quando será o repasse da unidade',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 16:18',
    entrou_financeiro: '2026-04-09 16:18',
    links: [],
  },
  {
    id: 14, ticket_id: 'XMCF6787', prioridade: 'P1',
    categoria: 'repasse', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'Repasse do finance em atraso',
    unidade: 'Borges & Co.',
    usuario: '',
    descricao: 'boa tarde! estamos com o repasse do cliente Eder Francisco Negocios Imobiliarios Ltda em atraso desde 31/03. ',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 15:46',
    entrou_financeiro: '2026-04-09 15:46',
    links: [],
  },
  {
    id: 15, ticket_id: 'KFAV2910', prioridade: 'P2',
    categoria: 'reembolso_royalties', subcategoria: '',
    status: 'nao_iniciado', dias: 4.0,
    titulo: 'Aguardando retorno TICKET SOSX4043',
    unidade: 'KTM & Co.',
    usuario: '',
    descricao: 'Tenho um ticket aberto referente um reembolso e estou sem retorno desde o dia 23/02. TICKET: SOSX4043',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-06 08:52',
    entrou_financeiro: '2026-04-06 08:52',
    links: [],
  },
  {
    id: 16, ticket_id: 'RUDC4890', prioridade: 'P2',
    categoria: 'finance', subcategoria: '',
    status: 'nao_iniciado', dias: 3.9,
    titulo: 'dar baixa nos pagamentos no finance',
    unidade: 'Wleite & Co',
    usuario: '',
    descricao: 'Agro ribeira:1º parcela	10/02/2026	Aberta	-	R$ 6.124,82 foi paga na data correta  Instituto Contagem:4º parcela	25/03/2026	Aberta	-	R$ 4.093,24 tb foi paga na data correta',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-06 11:51',
    entrou_financeiro: '2026-04-06 11:51',
    links: [],
  },
  {
    id: 17, ticket_id: 'PRMG6782', prioridade: 'P2',
    categoria: 'cancelamento_nf', subcategoria: '',
    status: 'pendencia', dias: 3.0,
    titulo: 'CANCELAMENTO DE NF INDEVIDA ',
    unidade: 'Jasson Oliveira & Co.',
    usuario: '',
    descricao: 'Solicito o cancelamento da NF 1829, CNPJ: 31.404.019/0001-27, NO VALOR DE 9.720,00 - EMITIDA INCORRETAMENTE  NF 1813 E 1830, CNPJ: 02.017.451/0001-67, VALOR: 21.600,00 - EMITIDA INCORRETAMENTE ',
    acoes: 'voltar para verificar se as nfs foram estornadas',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-07 09:26',
    entrou_financeiro: '2026-04-07 09:26',
    links: [],
  },
  {
    id: 18, ticket_id: 'TUDA0312', prioridade: 'P2',
    categoria: 'finance', subcategoria: '',
    status: 'pendencia', dias: 2.9,
    titulo: 'Pagamento Não Identificado',
    unidade: 'SBS & CO',
    usuario: '',
    descricao: 'Bom dia, tudo jóia? O cliente Tconnect Telecomunicacoes Ltda (53.558.593/0001-72) nos enviou o comprovante de pagamento da fatura no dia 01/04, conforme segue em anexo. Porém, no Finance ainda consta como inadimplente. Conseguimos verificar?',
    acoes: 'Olá,\n\nFoi feita a baixa do pagamento conforme comprovante enviado.\n\nAtenciosamente, time financeiro.',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-07 11:31',
    entrou_financeiro: '2026-04-07 11:31',
    links: [],
  },
  {
    id: 19, ticket_id: 'SRIY3190', prioridade: 'P2',
    categoria: 'reembolso_royalties', subcategoria: '',
    status: 'nao_iniciado', dias: 2.6,
    titulo: 'devolução de roy',
    unidade: 'Camargo Freitas & Associados',
    usuario: '',
    descricao: 'Solicito o reembolso para a Roy referente ao pagamento do cliente Soluqtion. No mês de fevereiro, foram gerados dois links de pagamento do fee no valor de R$ 1.380,00. O cliente informou que poderíamos considerar o pagamento para os meses 02 e 03, sem necessidade de devolução via Pix. No entanto, em',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-07 19:00',
    entrou_financeiro: '2026-04-07 19:00',
    links: [],
  },
  {
    id: 20, ticket_id: 'CYHL5088', prioridade: 'P2',
    categoria: 'reembolso_royalties', subcategoria: '',
    status: 'nao_iniciado', dias: 1.0,
    titulo: 'REEMBOLSO DE ROYALTIES',
    unidade: 'Verderosi & Co.',
    usuario: '',
    descricao: 'Cliente: Erl-comercio De Produtos Ltda - CNPJ: 19.776.815/0001-95   Recebemos recentemente a solicitação de reembolso por parte do cliente referente ao valor pago pelo projeto e ja fizemos a finalizamos esse reembolso para o cliente. Dessa forma, solicitamos, por gentileza, a devolução do valor de r',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 08:29',
    entrou_financeiro: '2026-04-09 08:29',
    links: [],
  },
  {
    id: 21, ticket_id: 'UQKE6131', prioridade: 'P2',
    categoria: 'finance', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'Pagamento pix - CLIENTE ALIA CAPITAL ',
    unidade: 'Peretto & Associados',
    usuario: '',
    descricao: 'Ola bom dia , tudo bem ?  Cliente Alia capital , fez por conta um pix para matriz do valor referente a março . Em anexo comprovante para estorno da parte fa franquia .',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 10:19',
    entrou_financeiro: '2026-04-09 10:19',
    links: [],
  },
  {
    id: 22, ticket_id: 'ODBF1532', prioridade: 'P2',
    categoria: 'cancelamento_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'Cancelamento NF',
    unidade: 'Alves & Co.',
    usuario: '',
    descricao: 'Prezados, foram emitidas duas notas do cliente 40.051.779/0001-99 - TRAVEL ROCK e outros clientes que pagaram as notas não foram emitidas. Preciso que regularizem a SAP e cancelem uma das notas notas emitidas deste cliente. Estamos tendo muuuuito problema com os clientes.',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:57',
    entrou_financeiro: '2026-04-09 11:58',
    links: [],
  },
  {
    id: 23, ticket_id: 'JVOT5585', prioridade: 'P2',
    categoria: 'cancelamento_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'Cancelar NF duplicada',
    unidade: 'undefined',
    usuario: '',
    descricao: 'Boa tarde, estamos com um problema grave com o cliente Fauko (Petroserv Comercial Ltda - CNPJ 64.955.255/0001-90). Mês passado teve nfs dupliciadas ref ao fee da assessoria e esse mês nfs duplicadas ref a ferramenta Botconversa. Precisamos cancelar uma das notas duplicadas. Isto está gerando bastant',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:57',
    entrou_financeiro: '2026-04-09 11:57',
    links: [],
  },
  {
    id: 24, ticket_id: 'HGSZ2727', prioridade: 'P2',
    categoria: 'cancelamento_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'NF FIMAQ SERVICOS ONSITE LTDA',
    unidade: 'Kloh Cerino & Associados',
    usuario: '',
    descricao: 'Olá, foi emitida 2 notas fiscais de royalties para o cliente FIMAQ SERVICOS ONSITE LTDA 36.904.825/0001-88, por favor cancelar uma nota',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:54',
    entrou_financeiro: '2026-04-09 11:54',
    links: [],
  },
  {
    id: 25, ticket_id: 'QWTH2121', prioridade: 'P2',
    categoria: 'cancelamento_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.8,
    titulo: 'Emitir e cancelar nfs ',
    unidade: 'Ferraz Piai & Co.',
    usuario: '',
    descricao: 'está faltando a emissão das nfs da matriz do seguinte cliente L J O A SERVICOS LTDA, CNPJ05.261.625/0001-20, precisa cancelar a nf do cliente de 425 e emitir uma no valor de 467,50 e outra da matriz no valor de 82,50 e uma da matriz no valor de 472,50',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 14:01',
    entrou_financeiro: '2026-04-09 14:01',
    links: [],
  },
  {
    id: 26, ticket_id: 'SBNV5912', prioridade: 'P2',
    categoria: 'ajuste_nf', subcategoria: '',
    status: 'pendencia', dias: 0.8,
    titulo: 'Retenção de NF',
    unidade: 'Canovas Mendes & Associados',
    usuario: '',
    descricao: 'Boa tarde, tudo bem?   Conforme o print, recebi essa mensagem questionando sobre base utilização para retenção da NF da matriz.',
    acoes: 'Olá,\n\nNo período de 01/03/26 a 10/03/2026, tivemos uma instabilidade que fez com que todas as NFs geradas nesse período saíssem com essa retenção. Ao ',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 14:46',
    entrou_financeiro: '2026-04-09 14:46',
    links: [],
  },
  {
    id: 27, ticket_id: 'XSBL6095', prioridade: 'P2',
    categoria: 'finance', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'Link para pix ',
    unidade: 'Nunes Carrano Fontes & Co',
    usuario: '',
    descricao: 'Solicito baixa do pagamento do mês de março do meu cliente \'Doce Encanto\' e o pix para pagamento do mes de abril, já que a opção de gerar o link nao esta disponível no Financer. Já solicitei suporte no grupo de cobrança do meu grupo no gchat mas nao tive retorno e a parcela vence amanha.   Segue com',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 16:05',
    entrou_financeiro: '2026-04-09 16:05',
    links: [],
  },
  {
    id: 28, ticket_id: 'MERS2265', prioridade: 'P2',
    categoria: 'cancelamento_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'Nota original cancelada. ',
    unidade: 'Amaral & Associados',
    usuario: '',
    descricao: 'time, solicito a nf 152777 (original) - consta como cancelada. cliente:  QUBIT MARKETPLACE DISTRIBUIDORA E C ',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 16:49',
    entrou_financeiro: '2026-04-09 16:49',
    links: [],
  },
  {
    id: 29, ticket_id: 'PSXN2942', prioridade: 'P2',
    categoria: 'cancelamento_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'Nota irregular',
    unidade: 'Affonso & Associados',
    usuario: '',
    descricao: 'Em fevereiro fiz um ticket (DJCN7559) solicitando nota do cliente VITRATO 24.511.912/0001-96 com o valor cheio para minha unidade.  Pois acabei de ver, que a nota desse cliente de fevereiro foi cancelada (pagamos imposto sob ela pois não sabia que tinha sido cancelada), e emitiram outra em 31/03 qua',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 15:47',
    entrou_financeiro: '2026-04-09 15:47',
    links: [],
  },
  {
    id: 30, ticket_id: 'YASX2252', prioridade: 'P2',
    categoria: 'finance', subcategoria: '',
    status: 'nao_iniciado', dias: 0.0,
    titulo: 'NF nao emitida',
    unidade: 'Davi & Co.',
    usuario: '',
    descricao: 'Peço gerar a NF do valor pago. Foi pago no Iugu e baixado manualmente no Finance.  Cliente Pfs Atividades De Condicionamento Fisico Ltda  CNPJ 35.763.116/0001-67',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 20:41',
    entrou_financeiro: '2026-04-10 08:28',
    links: [],
  },
  {
    id: 31, ticket_id: 'BOFF9945', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'pendencia', dias: 3.6,
    titulo: 'Emissão de NFs da Matriz para Unidade',
    unidade: 'Aguiar & Associados',
    usuario: '',
    descricao: 'Olá, emitimos algumas NF\'s no valor cheio para alguns clientes aqui pela Unidade. Preciso que a matriz emita as NF\'s da matriz aqui pela Unidade. Tem algumas NF\'s de Março e Abril. Segue abaixo link para verificar os clientes para emissão. https://docs.google.com/spreadsheets/d/1F0LyqIKZdjimvIYQ1pW8',
    acoes: 'Olá,\n\nTodas notas de ROY contra unidade são emitidas conforme pagamento. Verifiquei que as do cliente ZELLO de Março solicitadas foram emitidas ao lon',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-06 17:56',
    entrou_financeiro: '2026-04-06 17:56',
    links: [{"url": "https://docs.google.com/spreadsheets/d/1F0LyqIKZdjimvIYQ1pW8", "label": "Planilha Google", "icon": "\ud83d\udcca"}],
  },
  {
    id: 32, ticket_id: 'OULJ3481', prioridade: 'P3',
    categoria: 'finance', subcategoria: '',
    status: 'pendencia', dias: 3.6,
    titulo: 'Lançamento de cliente no Finance',
    unidade: 'Barbosa Souza & Co.',
    usuario: '',
    descricao: 'O cliente CBDL industria atualmente está com 2 contratos ativos conosco, um de R$9.190,00/mês e um de R$6.250,00/mês. No finance so está ativo o contrato de 9k, preciso que cadastrem o contrato de R$6.250,00, era pro cliente ter pago no dia 27/03, está em atraso e preciso de enviar o boleto para o c',
    acoes: 'AGUARDANDO CAIO SUBIR PROJETO DE 6.250 FALTANTE NO FINANCE.',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-06 17:39',
    entrou_financeiro: '2026-04-06 17:39',
    links: [],
  },
  {
    id: 33, ticket_id: 'OLUY8661', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 1.0,
    titulo: 'NF',
    unidade: 'Alves & Co.',
    usuario: '',
    descricao: 'Prezados, foi emitido via SAP a NF da unidade para o cliente ICONE TECNOLOGIA E PAGAMENTOS LTDA	- 19432487000100 mas não foi emitida a da matriz. Pode conferir e emitir, por favor? Outra coisa, depois de quanto tempo pago o boleto que a SAP emite a NF? Outra dúvida, foi divulgado que algumas prefeit',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 09:57',
    entrou_financeiro: '2026-04-09 09:57',
    links: [],
  },
  {
    id: 34, ticket_id: 'HGIU5877', prioridade: 'P3',
    categoria: 'finance', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'Trocar a conta de recebimento',
    unidade: 'Muniz & Associados',
    usuario: '',
    descricao: 'Substituir a conta atual, pois se refere a um CNPJ que será encerrado e estamos utilizando outra conta, conta atural para ser adicionada: SICOOB - CREDIAUC/SC 3067  CONTA 133.488-3 / PJ CNPJ: 60262715000144',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:37',
    entrou_financeiro: '2026-04-09 11:37',
    links: [],
  },
  {
    id: 35, ticket_id: 'ATEO4606', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'RAMAJ SEMI JOIAS E ACESSORIOS DE MODA LTDA',
    unidade: 'Nunes & Associados',
    usuario: '',
    descricao: 'RAMAJ SEMI JOIAS E ACESSORIOS DE MODA LTDA  por favor, cliente não recebeu a NF referente ao pagamento de março/26 poderiam emitir obrigada',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:17',
    entrou_financeiro: '2026-04-09 11:17',
    links: [],
  },
  {
    id: 36, ticket_id: 'TYIG0478', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'Notas 4x4 acessorios ',
    unidade: 'Peretto & Associados',
    usuario: '',
    descricao: 'ola bom dia ,  Solicitamos a emissao das notas do cliente 4x4 acessorios : Nota matriz ref pagamento de marco  nota franquia e matriz ref pagamento de abril .',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:45',
    entrou_financeiro: '2026-04-09 11:45',
    links: [],
  },
  {
    id: 37, ticket_id: 'ROOK2666', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'Nf\'s Epitacio Pescados Importadora Ltda',
    unidade: 'Azevedo Mendes & Associados',
    usuario: '',
    descricao: 'Estou precisando das NF\'s dos cliente Epitacio Pescados Importadora Ltda. Pagamentos de Janeiro, Fevereiro e Março. Cliente bastante reativo. ',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 12:35',
    entrou_financeiro: '2026-04-09 12:35',
    links: [],
  },
  {
    id: 38, ticket_id: 'DABN4747', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'NFS PENDENTES',
    unidade: 'Costa Silva Faria & Associados',
    usuario: '',
    descricao: 'Bom dia! Este chamado é em resposta a um aberto anteriormente (FYFJ4655) solicitando NFs de pagamentos realizados a matriz.  Segue dados planilhados e peço EXTREMA URGÊNCIA, já que o tempo de resposta do primeiro já foi ruim e essas NFs já deveriam ser emitidas sem necessidade de solicitação. ',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:57',
    entrou_financeiro: '2026-04-09 11:58',
    links: [],
  },
  {
    id: 39, ticket_id: 'ABCR6415', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'NF do cliente 40.780.814/0001-00',
    unidade: 'Affonso & Associados',
    usuario: '',
    descricao: 'Esse cliente pagou a primeira parcela de um escopo fechado no valor de R$ 5.001,97 no dia 01/04/2026, hoje é dia 08 e ainda não está pronta a nota fiscal dele. Eu disse que estava na fila para emissão da semana, mas pode checar para mim se a nota já irá ser emitida? Se não, podem emitir, por favor?',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:55',
    entrou_financeiro: '2026-04-09 11:56',
    links: [],
  },
  {
    id: 40, ticket_id: 'LGAD5474', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.9,
    titulo: 'CLIENTE ESPEL ELEVADORES -NF MES 3 e 4',
    unidade: 'Pizolato & Co.',
    usuario: '',
    descricao: 'Gostaria de solicitar apoio referente ao chamado SXFW8989, aberto em 06/04 às 10:53, para emissão da nota fiscal da unidade do cliente Espel (mês 03).  No dia 08/04 às 16:23, recebi o retorno informando que a NF havia sido enviada para processamento e que estaria disponível no SAP em até 1 hora. No ',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 11:46',
    entrou_financeiro: '2026-04-09 11:46',
    links: [],
  },
  {
    id: 41, ticket_id: 'YOCQ7466', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.8,
    titulo: 'Solicitação Notas Fiscais',
    unidade: 'Fares Araujo & Associados',
    usuario: '',
    descricao: 'Boa tarde!! Por gentileza, estou precisando de todas as notas fiscais emitidas para os clientes abaixo nos meses Janeiro 2026, Fevereiro 2026 e Março 2026.  1. Baobá Baby Ltda  44.471.358/0001-78 2. TEXTIL INES LTDA - Albamed   27.762.531/0001-78  No aguardo. ',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 14:37',
    entrou_financeiro: '2026-04-09 14:37',
    links: [],
  },
  {
    id: 42, ticket_id: 'BRSE7829', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.8,
    titulo: 'Nota Fiscal Visão Industrial',
    unidade: 'Godoy Rosendo & Co.',
    usuario: '',
    descricao: 'Foram emitidas duas notas fiscais pra VISAO INDUSTRIAL E COMERCIAL em março, e foi combinado entre o André e a Keila para não emitir em abril',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 14:15',
    entrou_financeiro: '2026-04-09 14:15',
    links: [],
  },
  {
    id: 43, ticket_id: 'RXQA4863', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'NF PEOPLE BROKER',
    unidade: 'Venturini & Associados',
    usuario: '',
    descricao: 'Boa tarde, prezados. Tudo bem?  Em 24/03/2026 fizemos uma compra de Investimento em People Broker. Total de R$ 1.766,43 em 3x de R$ 588,81  Até hoje não foi emitida a NF dela, pode nos enviar por gentileza. Comprovante em anexo.',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 15:02',
    entrou_financeiro: '2026-04-09 15:02',
    links: [],
  },
  {
    id: 44, ticket_id: 'JZFB8617', prioridade: 'P3',
    categoria: 'finance', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'Alteração de conta de recebimento',
    unidade: 'Bete & Co.',
    usuario: '',
    descricao: 'Pessoal boa tarde, tudo bem? Preciso alterar e centralizar todo recebimento do finance e iugu, nessa conta do banco sicoob.  Banco Sicoob Agencia 3191 Conta Corrente: 33.701-3 Assessoria de Marketing Thiago Bete Ltda',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 16:28',
    entrou_financeiro: '2026-04-09 16:28',
    links: [],
  },
  {
    id: 45, ticket_id: 'XWXW7753', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'NFS BLUSTRATUM',
    unidade: 'Lopes Santana & Associados',
    usuario: '',
    descricao: 'OLá time, coloquei em anexo o questionamento do cliente. CNPJ sob no 38.463.925/0001-41 ',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 15:15',
    entrou_financeiro: '2026-04-09 15:15',
    links: [],
  },
  {
    id: 46, ticket_id: 'ESSJ9823', prioridade: 'P3',
    categoria: 'finance', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'Revisão de lançamento e NFs - cliente WP MANAGER',
    unidade: 'Saman & Associados',
    usuario: '',
    descricao: 'O cliente WP MANAGER tem um contrato SABER e um contrato EXECUTAR.  SABER TOTAL: R$20.625,64 (dividido em 2x de R$10.312,82) Valor Fase: R$17.531,79 Valor Matriz: R$3.093,85  EXECUTAR TOTAL (ainda não iniciou): R$10.455,51 mensal Valor Fase: R$1.568,33 Valor Matriz: R$8.887,18  O cliente terminou de',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 15:31',
    entrou_financeiro: '2026-04-09 15:31',
    links: [],
  },
  {
    id: 47, ticket_id: 'YPRD3950', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'Cliente recebeu NF - indetificar!',
    unidade: 'Amaral & Associados',
    usuario: '',
    descricao: 'Olá, turma!  O cliente Qubit Marketplace Distribuidora e Comércio Ltda (34.480.288/0001-60) recebeu uma nota fiscal da matriz, de numeração 155987.  Alguém poderia verificar, por favor? Não tenho contexto sobre essa emissão.',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 16:47',
    entrou_financeiro: '2026-04-09 16:47',
    links: [],
  },
  {
    id: 48, ticket_id: 'SWEG6959', prioridade: 'P3',
    categoria: 'finance', subcategoria: '',
    status: 'nao_iniciado', dias: 0.7,
    titulo: 'Alteração de pagamento ',
    unidade: 'Coimbra & Associados',
    usuario: '',
    descricao: 'Gostaria de solicitar o descadastramento do cartão de crédito no finance da cliente Human Health Comercio De Produtos Naturais Ltda. ',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 15:20',
    entrou_financeiro: '2026-04-09 15:20',
    links: [],
  },
  {
    id: 49, ticket_id: 'FDKO3907', prioridade: 'P3',
    categoria: 'emissao_nf', subcategoria: '',
    status: 'nao_iniciado', dias: 0.6,
    titulo: 'Notas Fiscais de pagamentos já realizados BRASIL',
    unidade: 'Ames & Associados',
    usuario: '',
    descricao: 'Olá, tudo bem? Conforme solicitado no chamado ID: FGTD6803, estou enviando os comprovantes de pagamento do cliente. **BRASIL SUL FERRAGENS LTDA ** CNPJ:16839050000105  - Pago na IUGU  - Emitir as Notas fiscais.',
    acoes: '',
    pre_triagem: '',
    pipefy_url: '',
    criado_em: '2026-04-09 17:27',
    entrou_financeiro: '2026-04-09 17:27',
    links: [],
  },
]
